# Generated by Django 2.2.2 on 2019-06-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_by', models.CharField(max_length=50, verbose_name='uploaded_documents')),
                ('datestamp', models.DateTimeField(auto_now_add=True)),
                ('document', models.FileField(default='default.py', upload_to='quiz_file')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
