# Generated by Django 2.2.2 on 2019-07-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='pdf',
            field=models.FileField(upload_to='quiz_file'),
        ),
    ]
