# Generated by Django 2.2.2 on 2019-07-02 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190702_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='author',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='title',
        ),
    ]
